import { Inter } from "next/font/google";
import "../styles/globals.css";
import NavBar from "@components/navBar/navBar";
import Footer from "@components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ITAPP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <div className="ml-3 flex flex-col min-h-screen">
            <NavBar />
            <main className="app">{children}</main>
            <Footer />
          </div>
        </body>
      </html>
    </>
  );
}
